POST http://localhost:3000/company
Content-Type: application/json

{
    "name": "Test-Company",
    "phone": "99999999999",
    "cnpj": "00000000000000"
}

###
POST http://localhost:3000/sessions
Content-Type: application/json

{
    "companyCNPJ": "00000000000000",
    "email": "email@email.com",
    "password": "123456"

}